import { useEffect, useMemo, useState } from 'react';
import './liveClassroom.css';
import './classroomEvents.css';
import './analytics.css';
import ReportsCenter from './ReportsCenter';

const BASE_STUDENTS = [
  { id:1,name:'น้องอิม',number:1,team:'Coding Hero',level:5,exp:72,coin:420,badges:3,score:3,status:'online',location:'หมู่บ้าน',action:'กำลังสำรวจหมู่บ้าน',x:28,y:54,attempts:1,missions:8,trend:18 },
  { id:2,name:'น้องออฟตัน',number:2,team:'Robotics',level:4,exp:38,coin:315,badges:2,score:2,status:'online',location:'ห้องหุ่นยนต์',action:'กำลังสร้างรถขยะ',x:76,y:28,attempts:2,missions:6,trend:9 },
  { id:3,name:'น้องน้ำมนต์',number:3,team:'Young Scientist',level:6,exp:15,coin:540,badges:4,score:3,status:'online',location:'ห้องวิทยาศาสตร์',action:'กำลังทำแบบทดสอบ',x:48,y:23,attempts:1,missions:9,trend:22 },
  { id:4,name:'น้องปลาย',number:4,team:'Coding Hero',level:3,exp:81,coin:260,badges:2,score:2,status:'offline',location:'ออฟไลน์',action:'ออกจากระบบแล้ว',x:15,y:78,attempts:3,missions:4,trend:-4 },
  { id:5,name:'น้องน้ำขิง',number:5,team:'Green School',level:5,exp:44,coin:390,badges:3,score:3,status:'online',location:'จุดคัดแยกขยะ',action:'กำลังแยกขยะ',x:73,y:72,attempts:1,missions:8,trend:15 },
  { id:6,name:'น้องปลาเป้า',number:6,team:'Young Scientist',level:4,exp:62,coin:350,badges:2,score:2,status:'offline',location:'ออฟไลน์',action:'ออกจากระบบแล้ว',x:90,y:84,attempts:3,missions:5,trend:2 },
  { id:7,name:'น้องมิน',number:7,team:'Robotics',level:5,exp:20,coin:405,badges:3,score:3,status:'afk',location:'สนามโรงเรียน',action:'ไม่มีการเคลื่อนไหว',x:37,y:76,attempts:1,missions:7,trend:12 },
  { id:8,name:'น้องการ์ตูน',number:8,team:'Green School',level:4,exp:90,coin:375,badges:3,score:2,status:'online',location:'ห้องสมุด',action:'กำลังอ่านหนังสือ',x:19,y:24,attempts:2,missions:6,trend:6 },
  { id:9,name:'น้องฟิว',number:9,team:'Robotics',level:6,exp:48,coin:580,badges:5,score:3,status:'online',location:'ห้องหุ่นยนต์',action:'กำลังทดสอบหุ่นยนต์',x:82,y:39,attempts:1,missions:10,trend:25 },
];
const LOCATIONS=['หมู่บ้าน','ห้องวิทยาศาสตร์','ห้องหุ่นยนต์','ห้องสมุด','จุดคัดแยกขยะ','สนามโรงเรียน'];
const ACTIONS=['ได้รับ EXP +15','เข้าพื้นที่ใหม่','เริ่มทำภารกิจ','ตอบคำถามถูกต้อง','ได้รับ Badge'];
const TEMPLATES=[
  {title:'นักแยกสารตัวน้อย',description:'ไปที่ห้องวิทยาศาสตร์และทำแบบทดสอบให้ครบ',duration:20,exp:100,coin:50,target:'ทุกคน'},
  {title:'Coding Rescue Mission',description:'ร่วมทีมออกแบบคำสั่งช่วยเหลือผู้ประสบภัย',duration:25,exp:120,coin:60,target:'ทุกคน'},
  {title:'Green School Challenge',description:'รวบรวมและคัดแยกขยะให้ถูกประเภท',duration:15,exp:80,coin:40,target:'ทุกคน'},
];
const QUICK=['เริ่มกิจกรรมแล้ว','เหลือเวลา 5 นาที','ทุกคนกลับมาที่จุดรวม','เตรียมนำเสนอผลงาน','ภารกิจสำเร็จแล้ว'];
const WEEK=[52,61,68,76,84];
const timeNow=()=>new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
const addProgress=(s,exp,coin)=>{const total=s.exp+Number(exp||0);return{...s,level:s.level+Math.floor(total/100),exp:total%100,coin:s.coin+Number(coin||0)}};

export default function TeacherDashboard({onExit}){
  const [view,setView]=useState('overview');
  const [students,setStudents]=useState(BASE_STUDENTS);
  const [selected,setSelected]=useState(null);
  const [following,setFollowing]=useState(null);
  const [query,setQuery]=useState('');
  const [status,setStatus]=useState('all');
  const [team,setTeam]=useState('all');
  const [feed,setFeed]=useState([{id:1,time:'09:31',text:'น้องฟิว เข้าห้องหุ่นยนต์'},{id:2,time:'09:32',text:'น้องน้ำมนต์ ทำ Quiz ผ่าน'},{id:3,time:'09:34',text:'น้องอิม ได้รับ Badge'}]);
  const [events,setEvents]=useState([]);
  const [draft,setDraft]=useState(TEMPLATES[0]);
  const [activeId,setActiveId]=useState(null);
  const [remaining,setRemaining]=useState(0);
  const [announcement,setAnnouncement]=useState('');
  const [rewardTarget,setRewardTarget]=useState('all');
  const [rewardExp,setRewardExp]=useState(50);
  const [rewardCoin,setRewardCoin]=useState(20);

  useEffect(()=>{const timer=setInterval(()=>setStudents(current=>{const online=current.filter(s=>s.status!=='offline');if(!online.length)return current;const target=online[Math.floor(Math.random()*online.length)],location=LOCATIONS[Math.floor(Math.random()*LOCATIONS.length)],action=ACTIONS[Math.floor(Math.random()*ACTIONS.length)];setFeed(items=>[{id:Date.now(),time:timeNow(),text:`${target.name} ${action}`},...items].slice(0,12));return current.map(s=>s.id===target.id?{...s,location,action,x:Math.max(8,Math.min(92,s.x+Math.round(Math.random()*16-8))),y:Math.max(12,Math.min(86,s.y+Math.round(Math.random()*16-8)))}:s)}),4000);return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(!activeId||remaining<=0)return;const timer=setInterval(()=>setRemaining(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer)},[activeId,remaining]);
  useEffect(()=>{if(activeId&&remaining===0){setEvents(items=>items.map(e=>e.id===activeId?{...e,status:'finished'}:e));setActiveId(null)}},[activeId,remaining]);

  const filtered=useMemo(()=>students.filter(s=>`${s.name} ${s.team} ${s.location}`.toLowerCase().includes(query.toLowerCase())&&(status==='all'||s.status===status)),[students,query,status]);
  const counts={online:students.filter(s=>s.status==='online').length,afk:students.filter(s=>s.status==='afk').length,offline:students.filter(s=>s.status==='offline').length};
  const heatmap=LOCATIONS.map(location=>({location,count:students.filter(s=>s.status!=='offline'&&s.location===location).length})).sort((a,b)=>b.count-a.count);
  const active=events.find(e=>e.id===activeId);
  const title={overview:'ศูนย์ควบคุมชั้นเรียน',live:'Live Classroom Mission Control',events:'Classroom Event Control',analytics:'Learning Analytics',reports:'Reports & Export Center'}[view];
  const createEvent=e=>{e.preventDefault();setEvents(items=>[{...draft,id:Date.now(),status:'draft'},...items]);setFeed(items=>[{id:Date.now(),time:timeNow(),text:`ครูสร้างกิจกรรม “${draft.title}”`},...items])};
  const startEvent=item=>{setEvents(items=>items.map(e=>({...e,status:e.id===item.id?'active':e.status==='active'?'paused':e.status})));setActiveId(item.id);setRemaining(Number(item.duration)*60)};
  const finishEvent=item=>{setEvents(items=>items.map(e=>e.id===item.id?{...e,status:'finished'}:e));setStudents(items=>items.map(s=>s.status==='offline'?s:addProgress(s,item.exp,item.coin)));setActiveId(null);setRemaining(0)};
  const giveReward=e=>{e.preventDefault();const id=Number(rewardTarget);setStudents(items=>items.map(s=>rewardTarget==='all'||s.id===id?addProgress(s,rewardExp,rewardCoin):s))};
  const sendAnnouncement=text=>{const clean=(text??announcement).trim();if(!clean)return;setFeed(items=>[{id:Date.now(),time:timeNow(),text:`📢 ${clean}`},...items]);setAnnouncement('')};

  return <main className="teacher-shell">
    <aside className="teacher-sidebar"><div className="teacher-brand"><span>🌱</span><div><strong>BAO ONLINE</strong><small>Teacher Center</small></div></div><nav>
      {[['overview','📊 ภาพรวม'],['live','🛰️ ห้องเรียนสด'],['events','🎯 กิจกรรมชั้นเรียน'],['analytics','📈 วิเคราะห์ผล'],['reports','📄 รายงาน']].map(([key,label])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}>{label}</button>)}
    </nav><div className="teacher-account"><div className="teacher-avatar">ครู</div><div><strong>ครูสรา</strong><small>ผู้ดูแลชั้น ป.6</small></div></div><button className="teacher-exit" onClick={onExit}>← กลับหน้าหลัก</button></aside>
    <section className="teacher-main"><header className="teacher-topbar"><div><p>โรงเรียนบ้านเหล่าพ่อหา</p><h1>{title}</h1></div><div className="teacher-live"><span/> ระบบจำลองข้อมูลในเครื่อง</div></header>
      {active&&<section className="active-event-banner"><div><span>🔴 LIVE EVENT</span><strong>{active.title}</strong><small>{active.description}</small></div><div className="event-countdown">⏱ {String(Math.floor(remaining/60)).padStart(2,'0')}:{String(remaining%60).padStart(2,'0')}</div><button onClick={()=>setActiveId(null)}>⏸ หยุด</button><button onClick={()=>finishEvent(active)}>✅ จบ</button></section>}
      {view==='overview'&&<><section className="teacher-cards"><article><span>👨‍🎓</span><div><small>นักเรียนทั้งหมด</small><strong>{students.length}</strong><em>ชั้น ป.6</em></div></article><article><span>🟢</span><div><small>ออนไลน์</small><strong>{counts.online}</strong><em>{counts.afk} คน AFK</em></div></article><article><span>🎯</span><div><small>กิจกรรมทั้งหมด</small><strong>{events.length}</strong><em>{events.filter(e=>e.status==='finished').length} สำเร็จ</em></div></article><article><span>⭐</span><div><small>คะแนนเฉลี่ย</small><strong>{(students.reduce((a,s)=>a+s.score,0)/students.length).toFixed(1)}/3</strong><em>ผลล่าสุด</em></div></article></section><StudentTable students={filtered} query={query} setQuery={setQuery} status={status} setStatus={setStatus} inspect={setSelected}/></>}
      {view==='live'&&<><section className="live-summary"><span>🟢 ออนไลน์ <b>{counts.online}</b></span><span>🟡 AFK <b>{counts.afk}</b></span><span>⚪ ออฟไลน์ <b>{counts.offline}</b></span></section><section className="live-grid"><article className="live-map-card"><header><div><h2>🗺️ แผนที่ห้องเรียนสด</h2><p>คลิกนักเรียนเพื่อดูข้อมูล</p></div>{following&&<button onClick={()=>setFollowing(null)}>ยกเลิกติดตาม</button>}</header><div className="live-map"><span className="map-building lab">🧪<small>วิทย์</small></span><span className="map-building robot">🤖<small>หุ่นยนต์</small></span><span className="map-building library">📚<small>ห้องสมุด</small></span><span className="map-building recycle">♻️<small>คัดแยก</small></span>{students.filter(s=>s.status!=='offline').map(s=><button key={s.id} className={`map-student ${s.status} ${following?.id===s.id?'following':''}`} style={{left:`${s.x}%`,top:`${s.y}%`}} onClick={()=>setSelected(s)}>{s.name.replace('น้อง','').slice(0,2)}</button>)}</div></article><aside className="live-side"><article><h2>📡 Activity Feed</h2><div className="activity-feed">{feed.slice(0,8).map(i=><p key={i.id}><time>{i.time}</time><span>{i.text}</span></p>)}</div></article><article><h2>🔥 Classroom Heatmap</h2><div className="heatmap-list">{heatmap.map(i=><div key={i.location}><span>{i.location}</span><i><b style={{width:`${Math.max(5,i.count*28)}%`}}/></i><strong>{i.count}</strong></div>)}</div></article></aside></section></>}
      {view==='events'&&<section className="event-control-grid"><div className="event-control-main"><article className="event-card event-builder"><h2>🎯 สร้างกิจกรรม</h2><div className="template-row">{TEMPLATES.map(t=><button key={t.title} onClick={()=>setDraft(t)}>{t.title}</button>)}</div><form onSubmit={createEvent}><label>ชื่อกิจกรรม<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="wide-field">คำอธิบาย<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>เวลา<input type="number" value={draft.duration} onChange={e=>setDraft({...draft,duration:e.target.value})}/></label><label>EXP<input type="number" value={draft.exp} onChange={e=>setDraft({...draft,exp:e.target.value})}/></label><label>เหรียญ<input type="number" value={draft.coin} onChange={e=>setDraft({...draft,coin:e.target.value})}/></label><button className="event-create-button">＋ สร้างกิจกรรม</button></form></article><article className="event-card"><h2>📋 รายการกิจกรรม</h2><div className="event-list">{events.length===0&&<div className="event-empty">ยังไม่มีกิจกรรม</div>}{events.map(item=><div className={`event-list-item ${item.status}`} key={item.id}><div className="event-status-icon">{item.status==='active'?'🔴':item.status==='finished'?'✅':'📝'}</div><div><strong>{item.title}</strong><p>{item.description}</p><small>⏱ {item.duration} นาที · ⭐ {item.exp} EXP · 🪙 {item.coin}</small></div><div className="event-actions">{item.status!=='finished'&&<button onClick={()=>startEvent(item)}>▶ เริ่ม</button>}{item.status!=='finished'&&<button onClick={()=>finishEvent(item)}>✅ จบ</button>}</div></div>)}</div></article></div><aside className="event-control-side"><article className="event-card announcement-card"><h2>📢 ประกาศ</h2><div className="quick-announcements">{QUICK.map(t=><button key={t} onClick={()=>sendAnnouncement(t)}>{t}</button>)}</div><textarea value={announcement} onChange={e=>setAnnouncement(e.target.value)}/><button className="send-announcement" onClick={()=>sendAnnouncement()}>ส่งประกาศ</button></article><article className="event-card reward-card"><h2>🎁 แจกของรางวัล</h2><form onSubmit={giveReward}><select value={rewardTarget} onChange={e=>setRewardTarget(e.target.value)}><option value="all">ทั้งห้อง</option>{students.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><input type="number" value={rewardExp} onChange={e=>setRewardExp(Number(e.target.value))}/><input type="number" value={rewardCoin} onChange={e=>setRewardCoin(Number(e.target.value))}/><button>มอบรางวัล</button></form></article></aside></section>}
      {view==='analytics'&&<Analytics students={students} team={team} setTeam={setTeam} feed={feed} inspect={setSelected}/>}      
      {view==='reports'&&<ReportsCenter students={students} events={events} feed={feed}/>}    
    </section>
    {selected&&<div className="teacher-modal" onClick={()=>setSelected(null)}><section className="inspector-modal" onClick={e=>e.stopPropagation()}><button className="inspector-close" onClick={()=>setSelected(null)}>×</button><div className="student-big-avatar">{selected.name.slice(-1)}</div><h2>{selected.name}</h2><p>ป.6 · เลขที่ {selected.number} · {selected.team}</p><div className="student-detail-grid"><span><small>สถานะ</small><strong>{selected.status}</strong></span><span><small>ตำแหน่ง</small><strong>{selected.location}</strong></span><span><small>Level / EXP</small><strong>{selected.level} / {selected.exp}</strong></span><span><small>ภารกิจ</small><strong>{selected.missions}</strong></span><span><small>เหรียญ</small><strong>{selected.coin}</strong></span><span><small>Badge</small><strong>{selected.badges}</strong></span></div><div className="inspector-actions"><button onClick={()=>{setFollowing(selected);setView('live');setSelected(null)}}>👁 ติดตาม</button><button onClick={()=>{setRewardTarget(String(selected.id));setView('events');setSelected(null)}}>🎁 มอบรางวัล</button></div></section></div>}
  </main>
}

function StudentTable({students,query,setQuery,status,setStatus,inspect}){return <section className="teacher-panel"><div className="teacher-panel-head"><div><h2>รายชื่อนักเรียน</h2><p>ติดตามสถานะและความก้าวหน้า</p></div><div className="teacher-tools"><label>🔎<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหา"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">ทุกสถานะ</option><option value="online">ออนไลน์</option><option value="afk">AFK</option><option value="offline">ออฟไลน์</option></select></div></div><div className="teacher-table-wrap"><table className="teacher-table"><thead><tr><th>นักเรียน</th><th>สถานะ</th><th>ทีม</th><th>Level / EXP</th><th>ตำแหน่ง</th><th>คะแนน</th><th/></tr></thead><tbody>{students.map(s=><tr key={s.id}><td><div className="student-name"><span>{s.name.slice(-1)}</span><div><strong>{s.name}</strong><small>เลขที่ {s.number}</small></div></div></td><td><span className={`status-pill ${s.status}`}>● {s.status}</span></td><td><span className="team-pill">{s.team}</span></td><td>Lv.{s.level} · {s.exp} EXP</td><td><strong>{s.location}</strong><small className="activity-text">{s.action}</small></td><td>{s.score}/3</td><td><button className="detail-button" onClick={()=>inspect(s)}>ดูข้อมูล</button></td></tr>)}</tbody></table></div></section>}

function Analytics({students,team,setTeam,feed,inspect}){const teams=[...new Set(students.map(s=>s.team))],visible=team==='all'?students:students.filter(s=>s.team===team),avg=visible.reduce((a,s)=>a+s.score,0)/Math.max(1,visible.length),needs=visible.filter(s=>s.score<3||s.attempts>=3||s.trend<0),ranked=[...visible].sort((a,b)=>(b.score*100+b.level*10+b.exp)-(a.score*100+a.level*10+a.exp));return <section className="analytics-page"><div className="analytics-toolbar"><div><h2>📈 ภาพรวมการเรียนรู้</h2><p>วิเคราะห์คะแนน ความก้าวหน้า และภารกิจ</p></div><select value={team} onChange={e=>setTeam(e.target.value)}><option value="all">ทุกทีม</option>{teams.map(t=><option key={t}>{t}</option>)}</select></div><section className="analytics-kpis"><article><small>คะแนนเฉลี่ย</small><strong>{avg.toFixed(1)}/3</strong><em>{visible.length} คน</em></article><article><small>อัตราจบบทเรียน</small><strong>{Math.round(visible.filter(s=>s.score>=3).length/Math.max(1,visible.length)*100)}%</strong><em>ผ่านเกณฑ์</em></article><article><small>Level เฉลี่ย</small><strong>{(visible.reduce((a,s)=>a+s.level,0)/Math.max(1,visible.length)).toFixed(1)}</strong><em>ความก้าวหน้า</em></article><article><small>ควรติดตาม</small><strong>{needs.length}</strong><em>นักเรียน</em></article></section><section className="analytics-grid"><article className="analytics-card"><h2>📅 แนวโน้มรายสัปดาห์</h2><div className="score-bars">{['จันทร์','อังคาร','พุธ','พฤหัสบดี','ศุกร์'].map((d,i)=><div className="score-bar" key={d}><span>{d}</span><i><b style={{width:`${WEEK[i]}%`}}/></i><strong>{WEEK[i]}%</strong></div>)}</div></article><article className="analytics-card"><h2>⚠️ นักเรียนที่ควรติดตาม</h2><div className="needs-list">{needs.map(s=><div className="needs-item" key={s.id}><span>{s.name.slice(-1)}</span><div><strong>{s.name}</strong><small>คะแนน {s.score}/3 · แนวโน้ม {s.trend}%</small></div><button onClick={()=>inspect(s)}>ดูข้อมูล</button></div>)}</div></article></section><article className="analytics-card"><h2>🥇 ตารางคะแนนรายบุคคล</h2><div className="analytics-table-wrap"><table className="analytics-table"><thead><tr><th>อันดับ</th><th>นักเรียน</th><th>ทีม</th><th>คะแนน</th><th>ภารกิจ</th><th>Level / EXP</th><th/></tr></thead><tbody>{ranked.map((s,i)=><tr key={s.id}><td>{i+1}</td><td>{s.name}</td><td>{s.team}</td><td>{s.score}/3</td><td>{s.missions}</td><td>Lv.{s.level} · {s.exp}</td><td><button className="detail-button" onClick={()=>inspect(s)}>วิเคราะห์</button></td></tr>)}</tbody></table></div></article><article className="analytics-card"><h2>🕘 Activity History</h2><div className="activity-history">{feed.map(i=><p key={i.id}><time>{i.time}</time><span>{i.text}</span></p>)}</div></article></section>}
